FROM node:alpine as build

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

RUN ["npm", "run", "build"]

FROM nginx

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

# docker build -t nginxreact -f Dockerfile.prod .
#  docker run -p 80:80 nginxreact
