version: '3.9'
services:
  client:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  test:
    build: .
    command: [ "npm", "run", "test" ]
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
    stdin_open: true
    tty: true
    # docker attach
